
array_layout = "Block"
array_width = 100
chain_one_line_max = 100
closure_block_indent_threshold = -1
comment_width = 120

fn_args_density = "Vertical"
fn_args_layout = "Block"
fn_args_paren_newline = false
fn_brace_style = "PreferSameLine"
fn_call_style = "Block"
fn_call_width = 200

generics_indent = "Block"
item_brace_style = "PreferSameLine"
max_width = 200
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
single_line_if_else_max_width = 0
skip_children = false
space_after_bound_colon = true
space_before_bound = false
struct_lit_width = 100
struct_variant_width = 100
trailing_comma = "Never"
where_density = "Compressed"
wrap_comments = true
write_mode = "Overwrite"
