language: rust
sudo: true
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV=true
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo install --debug cargo-make
  - cargo make ci-flow
